# Generated by Django 4.2.7 on 2025-08-05 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, help_text='Cover letter content')),
                ('resume_url', models.URLField(blank=True, help_text='URL to resume file')),
                ('portfolio_url', models.URLField(blank=True, help_text='Portfolio website URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('interviewed', 'Interviewed'), ('rejected', 'Rejected'), ('accepted', 'Accepted'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from HR/Admin')),
                ('rejection_reason', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('availability_date', models.DateField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'db_table': 'applications',
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['status'], name='application_status_e61111_idx'), models.Index(fields=['applied_at'], name='application_applied_0de066_idx'), models.Index(fields=['job', 'status'], name='application_job_id_606b4d_idx')],
                'unique_together': {('job', 'applicant')},
            },
        ),
    ]
