# Generated by Django 4.2.7 on 2025-08-05 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_remote', models.BooleanField(default=False)),
                ('remote_type', models.CharField(choices=[('fully_remote', 'Fully Remote'), ('hybrid', 'Hybrid'), ('on_site', 'On Site')], default='on_site', max_length=20)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship')], default='full_time', max_length=50)),
                ('experience_level', models.CharField(choices=[('entry_level', 'Entry Level'), ('mid_level', 'Mid Level'), ('senior_level', 'Senior Level'), ('executive', 'Executive')], default='mid_level', max_length=50)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=3)),
                ('salary_type', models.CharField(choices=[('hourly', 'Hourly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='yearly', max_length=20)),
                ('show_salary', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed'), ('expired', 'Expired')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(default=False)),
                ('application_url', models.URLField(blank=True, help_text='External application URL')),
                ('application_email', models.EmailField(blank=True, max_length=254)),
                ('accept_applications', models.BooleanField(default=True)),
                ('skills_required', models.TextField(blank=True, help_text='Comma-separated list of skills')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('applications_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'status'], name='jobs_is_acti_368e74_idx'), models.Index(fields=['location'], name='jobs_locatio_8650dd_idx'), models.Index(fields=['job_type'], name='jobs_job_typ_e7f4d4_idx'), models.Index(fields=['experience_level'], name='jobs_experie_96c339_idx'), models.Index(fields=['created_at'], name='jobs_created_7c32a5_idx'), models.Index(fields=['expires_at'], name='jobs_expires_503a37_idx')],
            },
        ),
    ]
