# Generated by Django 4.2.7 on 2025-08-06 16:21

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo image', null=True, upload_to=companies.models.company_logo_upload_path),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo_url',
            field=models.URLField(blank=True, help_text='External logo URL (used if no logo file uploaded)'),
        ),
    ]
